package test.beastfx.app.inputeditor;


import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.File;
import java.net.URL;

import org.junit.jupiter.api.Test;

import beastfx.app.inputeditor.BeautiDoc;

/**
 * Tests the file sniffing that decides whether a file dropped on BEAUti is a complete
 * BEAST analysis (to be loaded like File/Load does) or an alignment (to be imported).
 */
public class BeautiAnalysisFileTest {

	private File resource(String name) {
		URL url = BeautiAnalysisFileTest.class.getClassLoader()
				.getResource("beastfx/app/inputeditor/dropped/" + name);
		assertNotNull(url, "test resource " + name + " not found on classpath");
		return new File(url.getFile());
	}

	@Test
	public void testBeautiXMLIsRecognisedAsAnalysis() {
		assertTrue(BeautiDoc.isBeautiAnalysisFile(resource("beauti-analysis.xml")));
	}

	@Test
	public void testXMLWithoutBeautiTemplateIsNotAnAnalysis() {
		// a BEAST XML that was not generated by BEAUti: leave it to the alignment importers
		assertFalse(BeautiDoc.isBeautiAnalysisFile(resource("plain-beast.xml")));
	}

	@Test
	public void testNexusIsNotAnAnalysis() {
		assertFalse(BeautiDoc.isBeautiAnalysisFile(resource("alignment.nex")));
	}

	@Test
	public void testMissingFileIsNotAnAnalysis() {
		assertFalse(BeautiDoc.isBeautiAnalysisFile(new File("does-not-exist.xml")));
	}
}
