#!/bin/sh

if [ -z "$BUNDLE_HOME" ]; then
	## resolve links - $0 may be a link to application
	PRG="$0"

	# need this for relative symlinks
	while [ -h "$PRG" ] ; do
	    ls=$(ls -ld "$PRG")
	    link=$(expr "$ls" : '.*-> \(.*\)$')
	    if expr "$link" : '/.*' > /dev/null; then
		PRG="$link"
	    else
		PRG="$(dirname "$PRG")/$link"
	    fi
	done

	# make it fully qualified
	saveddir=$(pwd)
	BUNDLE_HOME=$(cd "$(dirname "$PRG")/.." && pwd)
	cd "$saveddir"
fi

JAVA_HOME="$BUNDLE_HOME/jre"
export JAVA_HOME
JAVA="$JAVA_HOME/bin/java"
exec "$JAVA" -Xmx4g -Duser.language=en -Dfile.encoding=UTF-8 \
    -jar "$BUNDLE_HOME/lib/DensiTree.jar" "$@"
