#!/bin/sh

if [ -z "$BUNDLE_HOME" ]; then
	## resolve links - $0 may be a link to application
	PRG="$0"

	# need this for relative symlinks
	while [ -h "$PRG" ] ; do
	    ls=$(ls -ld "$PRG")
	    link=$(expr "$ls" : '.*-> \(.*\)$')
	    if expr "$link" : '/.*' > /dev/null; then
		PRG="$link"
	    else
		PRG="$(dirname "$PRG")/$link"
	    fi
	done

	# make it fully qualified
	saveddir=$(pwd)
	BUNDLE_HOME=$(cd "$(dirname "$PRG")/.." && pwd)
	cd "$saveddir"
fi

JAVA_HOME="$BUNDLE_HOME/jre"
export JAVA_HOME
JAVA="$JAVA_HOME/bin/java"
APP="$BUNDLE_HOME/lib"

# use BEAGLE_LIB if the BEAGLE library is not in a standard location
if [ -n "$BEAGLE_LIB" ]; then
	if [ -n "$BEAST_EXTRA_LIBS" ]; then
		BEAST_EXTRA_LIBS="$BEAST_EXTRA_LIBS:$BEAGLE_LIB"
	else
		BEAST_EXTRA_LIBS="$BEAGLE_LIB"
	fi
fi

# Explicitly add /usr/local/lib to library search path to ensure
# beast continues to find beagle when installed here.
if [ -z "$LD_LIBRARY_PATH" ]; then
    export LD_LIBRARY_PATH=/usr/local/lib
else
    export LD_LIBRARY_PATH="$LD_LIBRARY_PATH":/usr/local/lib
fi

if [ -n "$BEAST_EXTRA_LIBS" ]; then
  exec "$JAVA" --module-path "$APP" --add-modules ALL-MODULE-PATH \
      -Xss256m -Xmx8g -Djava.library.path="$BEAST_EXTRA_LIBS" -Duser.language=en -Dfile.encoding=UTF-8 \
      -m beast.pkgmgmt/beast.pkgmgmt.launcher.AppLauncherLauncher beastfx.app.tools.LogAnalyser "$@"
else
  exec "$JAVA" --module-path "$APP" --add-modules ALL-MODULE-PATH \
      -Xss256m -Xmx8g -Duser.language=en -Dfile.encoding=UTF-8 \
      -m beast.pkgmgmt/beast.pkgmgmt.launcher.AppLauncherLauncher beastfx.app.tools.LogAnalyser "$@"
fi
